# Generated by Django 4.2.16 on 2026-09-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Soru')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Anket',
                'verbose_name_plural': 'Anketler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Seçenek metni')),
                ('vote_count', models.PositiveIntegerField(default=0, verbose_name='Oy sayısı')),
            ],
            options={
                'verbose_name': 'Anket seçeneği',
                'verbose_name_plural': 'Anket seçenekleri',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_token', models.CharField(blank=True, default='', max_length=128, verbose_name='Anonim token')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oy tarihi')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.polloption', verbose_name='Seçenek')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll', verbose_name='Anket')),
            ],
            options={
                'verbose_name': 'Oy',
                'verbose_name_plural': 'Oylar',
            },
        ),
    ]
