# Generated by Django 4.2.16 on 2026-09-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.CharField(choices=[('genel', 'Genel'), ('kariyer', 'Kariyer'), ('iliski', 'İlişki'), ('teknoloji', 'Teknoloji'), ('alisveris', 'Alışveriş'), ('diger', 'Diğer')], default='genel', max_length=20, verbose_name='Kategori'),
        ),
    ]
